# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dfd93a7dfcc2c12a82705440673d93e045dd710313140222daa7e4cdbde4ef4f19d7e8be330aa8e2d1d242e573c4ee4c857cf081f4e725e5f93255750273137

test:
  secret_key_base: 49b954f139599a2823badf39cc8c7f4a80ef614fe2309dc4fe44043f352d00329b0945a837b6f2a085c0d0af1f8e8291faafd7fc6b1cee997448f9427af4fcac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a7fd93a7dfcc2c12a82705440673d93e045dd710313140222daa7e456bde4ef4f19d7e8be330aa8e2d1d242e573c4ee4c857cf081f4e725e5f93255750273132
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
