pid: /var/run/geoip.pid
timeout: 30
wait: 30
log: log/thin/geoip.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
servers: 4
daemonize: true
chdir: /usr/share/nginx/geoip/current
socket: /var/run/geoip.sock