pid: /var/run/geoip.pid
timeout: 10
wait: 10
log: log/thin/geoip.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 100
servers: 8
daemonize: true
chdir: /usr/share/nginx/geoip/current
socket: /var/run/geoip.sock